apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../default
  - serviceaccounts.yaml
  - postgres.yaml
  - applicationidentities.yaml

patches:
  - path: manager_kind_patch.yaml
    target:
      kind: Deployment
      name: dis-pgsql-operator-controller-manager
      namespace: dis-pgsql-operator-system
