apiVersion: apps/v1
kind: Deployment
metadata:
  name: dis-pgsql-operator-controller-manager
  namespace: dis-pgsql-operator-system
spec:
  template:
    spec:
      containers:
        - name: manager
          imagePullPolicy: Never
          args:
            - "--use-az-fakes"
          env:
            - name: DISPG_AZURE_SUBSCRIPTION_ID
              value: "fake-subscription"
            - name: DISPG_DB_RESOURCE_GROUP
              value: "fake-rg"
            - name: DISPG_DB_VNET_NAME
              value: "fake-db-vnet"
            - name: DISPG_AKS_VNET_NAME
              value: "fake-aks-vnet"
            - name: DISPG_AZURE_TENANT_ID
              value: "fake-tenant"
            - name: DISPG_AKS_RESOURCE_GROUP
              value: "fake-aks-rg"
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
