apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: redirect-grafana-fqdn-to-azure-grafana
  namespace: traefik
spec:
  entryPoints:
    - https
  routes:
    - kind: Rule
      match: Host(`${REDIRECT_GRAFANA_FROM_FQDN}`)
      middlewares:
        - name: redirect-grafana-fqdn-to-azure-grafana
          namespace: traefik
      services:
        - kind: TraefikService
          name: noop@internal
