---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
  name: apiversions.apim.dis.altinn.cloud
spec:
  group: apim.dis.altinn.cloud
  names:
    kind: ApiVersion
    listKind: ApiVersionList
    plural: apiversions
    singular: apiversion
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.provisioningState
      name: State
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ApiVersion is the Schema for the apiversions API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: spec defines the desired state of ApiVersion
            properties:
              apiType:
                default: http
                description: ApiType - Type of API.
                enum:
                - graphql
                - http
                - websocket
                type: string
              apiVersionScheme:
                default: Segment
                description: ApiVersionScheme - The scheme of the API version. Default
                  value is "Segment".
                type: string
              apiVersionSetId:
                description: ApiVersionSetId - The identifier of the API Version Set
                  this version is a part of.
                type: string
              contact:
                description: Contact - Contact details of the API owner.
                properties:
                  email:
                    description: The email address of the contact person/organization.
                      MUST be in the format of an email address
                    type: string
                  name:
                    description: The identifying name of the contact person/organization
                    type: string
                  url:
                    description: The URL pointing to the contact information. MUST
                      be in the format of a URL
                    type: string
                type: object
              content:
                description: Content - The contents of the API. The value is a string
                  containing the content of the API.
                minLength: 1
                type: string
              contentFormat:
                default: openapi+json
                description: ContentFormat - Format of the Content in which the API
                  is getting imported. Default value is openapi+json.
                type: string
              description:
                description: Description - Description of the API Version. May include
                  its purpose, where to get more information, and other relevant information.
                type: string
              diagnostics:
                description: Diagnostics - The API Version Diagnostic settings.
                properties:
                  backend:
                    description: Backend Diagnostic settings for incoming/outgoing
                      HTTP messages to the Backend. If not specified, the default
                      values are set at runtime.
                    properties:
                      request:
                        description: Request - Diagnostic settings for incoming HTTP
                          messages. If not specified, the default values are used.
                        properties:
                          headers:
                            description: Headers - Array of HTTP Headers to log. Defaults
                              to [Ocp-Apim-Subscription-Key, Content-Type, X-Forwarded-For].
                              Defaults set at runtime.
                            items:
                              type: string
                            type: array
                        type: object
                      response:
                        description: Response - Diagnostic settings for outgoing HTTP
                          messages. If not specified, the default values are used.
                        properties:
                          headers:
                            description: Headers - Array of HTTP Headers to log. Defaults
                              to [Ocp-Apim-Subscription-Key, Content-Type, X-Forwarded-For].
                              Defaults set at runtime.
                            items:
                              type: string
                            type: array
                        type: object
                    type: object
                  enableMetrics:
                    description: EnableMetrics - Indicates if metrics should be collected.
                      Defaults to true, value set at runtime.
                    type: boolean
                  frontend:
                    description: Frontend Diagnostic settings for incoming/outgoing
                      HTTP messages to the Gateway. If not specified, the default
                      values are set at runtime.
                    properties:
                      request:
                        description: Request - Diagnostic settings for incoming HTTP
                          messages. If not specified, the default values are used.
                        properties:
                          headers:
                            description: Headers - Array of HTTP Headers to log. Defaults
                              to [Ocp-Apim-Subscription-Key, Content-Type, X-Forwarded-For].
                              Defaults set at runtime.
                            items:
                              type: string
                            type: array
                        type: object
                      response:
                        description: Response - Diagnostic settings for outgoing HTTP
                          messages. If not specified, the default values are used.
                        properties:
                          headers:
                            description: Headers - Array of HTTP Headers to log. Defaults
                              to [Ocp-Apim-Subscription-Key, Content-Type, X-Forwarded-For].
                              Defaults set at runtime.
                            items:
                              type: string
                            type: array
                        type: object
                    type: object
                  loggerName:
                    description: LoggerName - The name of the logger to receive the
                      diagnostic data. Operator will lookup the loggerId by this name.
                      Default logger set at runtime
                    type: string
                  samplingPercentage:
                    description: SamplingPercentage - Percentage of the calls to log.
                      Default value set at runtime.
                    format: int32
                    maximum: 100
                    minimum: 0
                    type: integer
                type: object
              displayName:
                description: DisplayName - The display name of the API Version. This
                  name is used by the developer portal as the API Version name.
                minLength: 1
                type: string
              isCurrent:
                default: true
                description: IsCurrent - Indicates if API Version is the current api
                  version. Default value is true.
                type: boolean
              name:
                description: |-
                  INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                  Important: Run "make" to regenerate code after modifying this file
                  Name - Name of the API Version. If no name is provided this will be the default version
                type: string
              path:
                description: Path - API prefix. The value is combined with the API
                  version to form the URL of the API endpoint.
                minLength: 1
                type: string
              policies:
                description: Policies - The API Version Policy description.
                properties:
                  policyContent:
                    description: PolicyContent - The contents of the Policy as string.
                    type: string
                  policyFormat:
                    default: rawxml
                    description: PolicyFormat - Format of the Policy in which the
                      API is getting imported.
                    enum:
                    - xml
                    - xml-link
                    - rawxml
                    - rawxml-link
                    type: string
                  policyValues:
                    description: PolicyValues Value references for replacing policy
                      expressions.
                    items:
                      description: PolicyValue defines the desired state of ApiVersion
                      properties:
                        idFromBackend:
                          description: IdFromBackend references a backend defined
                            in the same namespace. The PolicyValue.Name will be replaced
                            in the ApiPolicySpec with the id of the backend in Azure.
                          properties:
                            name:
                              description: Name
                              type: string
                            namespace:
                              description: Namespace Namespace where the backend is
                                defined. Default value is the same namespace as the
                                API Version.
                              type: string
                          required:
                          - name
                          type: object
                        name:
                          description: Name - The key of the policy value.
                          type: string
                        value:
                          description: Value - The value of the policy value.
                          type: string
                      required:
                      - name
                      type: object
                      x-kubernetes-validations:
                      - message: Either value or idFromBackend must be set, but not
                          both
                        rule: '!has(self.value) || !has(self.idFromBackend)'
                      - message: Either value or idFromBackend must be set
                        rule: has(self.value) || has(self.idFromBackend)
                    type: array
                required:
                - policyContent
                type: object
              products:
                description: Products - Products that the API is associated with.
                  Products are groups of APIs.
                items:
                  type: string
                type: array
              protocols:
                default:
                - https
                description: Protocols - Describes protocols over which API is made
                  available. Default value is https.
                items:
                  type: string
                type: array
              serviceUrl:
                description: ServiceUrl - Absolute URL of the backend service implementing
                  this API. Cannot be more than 2000 characters long.
                maxLength: 2000
                type: string
              subscriptionRequired:
                default: true
                description: SubscriptionRquired - Indicates if subscription is required
                  to access the API. Default value is true.
                type: boolean
            required:
            - apiVersionSetId
            - content
            - displayName
            - path
            type: object
          status:
            description: status defines the observed state of ApiVersion
            properties:
              conditions:
                description: |-
                  conditions represent the current state of the ApiVersion resource.
                  Each condition has a unique type and reflects the status of a specific aspect of the resource.

                  Standard condition types include:
                  - "Available": the resource is fully functional
                  - "Progressing": the resource is being created or updated
                  - "Degraded": the resource failed to reach or maintain its desired state

                  The status of each condition is one of True, False, or Unknown.
                items:
                  description: Condition contains details for one aspect of the current
                    state of this API Resource.
                  properties:
                    lastTransitionTime:
                      description: |-
                        lastTransitionTime is the last time the condition transitioned from one status to another.
                        This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: |-
                        message is a human readable message indicating details about the transition.
                        This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: |-
                        observedGeneration represents the .metadata.generation that the condition was set based upon.
                        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                        with respect to the current state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: |-
                        reason contains a programmatic identifier indicating the reason for the condition's last transition.
                        Producers of specific condition types may define expected values and meanings for this field,
                        and whether the values are considered a guaranteed API.
                        The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - type
                x-kubernetes-list-type: map
              lastAppliedPolicyBase64:
                description: LastAppliedPolicyBase64 - The base64 of the last applied
                  spec.
                type: string
              lastAppliedPolicySha:
                description: LastAppliedPolicySha - The sha256 of the last applied
                  policy.
                type: string
              lastAppliedSpecSha:
                description: LastAppliedSpecSha - The sha256 of the last applied spec.
                type: string
              provisioningState:
                description: 'ProvisioningState - The provisioning state of the API.
                  Possible values are: Succeeded, Failed, Updating, Deleting.'
                type: string
              resumeToken:
                description: ResumeToken - The token used to track long-running operations.
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
