apiVersion: storage.dis.altinn.cloud/v1alpha1
kind: Database
metadata:
  name: db1
  namespace: default
spec:
  version: 16
  serverType: prod
  backupRetentionDays: 30
  storage:
    sizeGB: 128
    tier: P10
  auth:
    admin:
      identity:
        identityRef:
          name: adminidentity
    user:
      identity:
        identityRef:
          name: useridentity
---
apiVersion: storage.dis.altinn.cloud/v1alpha1
kind: Database
metadata:
  name: db2
  namespace: default
spec:
  version: 17
  serverType: dev
  enableExtensions:
    - hstore
    - pg_cron
  storage:
    sizeGB: 32
    tier: P10
  auth:
    admin:
      identity:
        identityRef:
          name: adminidentity
    user:
      identity:
        identityRef:
          name: useridentity2
---
apiVersion: storage.dis.altinn.cloud/v1alpha1
kind: Database
metadata:
  name: db4
  namespace: default
spec:
  version: 17
  serverType: dev
  storage:
    sizeGB: 32
    tier: P80
  auth:
    admin:
      identity:
        identityRef:
          name: adminidentity
    user:
      identity:
        identityRef:
          name: useridentity
---
apiVersion: storage.dis.altinn.cloud/v1alpha1
kind: Database
metadata:
  name: db5
  namespace: default
spec:
  version: 17
  serverType: dev
  storage:
    sizeGB: 64
    tier: P6
  auth:
    admin:
      identity:
        identityRef:
          name: adminidentity
    user:
      identity:
        identityRef:
          name: useridentity2
# ---
# apiVersion: storage.dis.altinn.cloud/v1alpha1
# kind: Database
# metadata:
#   name: db6
#   namespace: test
# spec:
#   version: 17
#   serverType: dev
#   auth:
#     admin:
#       identity:
#         identityRef:
#           name: adminidentity
#     user:
#       identity:
#         identityRef:
#           name: useridentity
# ---
# apiVersion: storage.dis.altinn.cloud/v1alpha1
# kind: Database
# metadata:
#   name: db9
#   namespace: test
# spec:
#   version: 17
#   serverType: dev
#   auth:
#     admin:
#       identity:
#         identityRef:
#           name: adminidentity
#     user:
#       identity:
#         identityRef:
#           name: useridentity2
