apiVersion: storage.dis.altinn.cloud/v1alpha1
kind: Database
metadata:
  labels:
    app.kubernetes.io/name: dis-pgsql-operator
    app.kubernetes.io/managed-by: kustomize
  name: database-sample
spec:
  # TODO(user): Add fields here
