name: Altinn K6 Lib Release

on:
  push:
    tags:
      - "altinn-k6-lib-*"

permissions:
  contents: write

jobs:
  checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: libs/k6
    if: startsWith(github.ref, 'refs/tags/altinn-k6-lib-')
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Use Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: "24.x"

      - name: Dependencies
        run: yarn

      - name: Check build
        run: yarn build

      - name: Create Release & Upload Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          VERSION="${GITHUB_REF##*/}"
          gh release create "$VERSION" ./build/* --target "$GITHUB_SHA" --title "$VERSION"
