name: Dis Pgsql Lint and Test


on:
  push:
    branches:
      - main
    paths:
      - services/dis-pgsql-operator/**
      - .github/workflows/dis-pgsql-lint-test.yml
  pull_request:
    branches:
      - main
    paths:
      - services/dis-pgsql-operator/**
      - .github/workflows/dis-pgsql-lint-test.yml

permissions:
  contents: read

jobs:
  lint:
    name: Run linter on Ubuntu
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/dis-pgsql-operator
    steps:
      - name: Clone the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: 'services/dis-pgsql-operator/go.mod'
          cache-dependency-path: 'services/dis-pgsql-operator/go.sum'

      - name: Run linter
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: v2.1.6
          working-directory: services/dis-pgsql-operator
  test:
    name: Run tests on Ubuntu
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/dis-pgsql-operator
    steps:
      - name: Clone the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: 'services/dis-pgsql-operator/go.mod'
          cache-dependency-path: 'services/dis-pgsql-operator/go.sum'

      - name: Running Tests
        run: |
          go mod tidy
          make test
