name: Scan/Release Dis Pgsql Operator Image and Build Kustomize OCI Artifact

env:
  FLUX_ARTIFACT_NAME: dis/kustomize/dis-pgsql-operator

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/dis-pgsql-release.yml
      - services/dis-pgsql-operator/**
      - .github/workflows/reusable-image-scan-and-release-ghcr.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/dis-pgsql-release.yml
      - services/dis-pgsql-operator/**
      - .github/workflows/reusable-image-scan-and-release-ghcr.yml
    tags:
      - "dis-pgsql-*"
      - "kustomize-dis-pgsql-*"

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-release-image:
    name: Build, scan and release
    uses: ./.github/workflows/reusable-image-scan-and-release-ghcr.yml
    with:
      release_latest: true
      image_name: dis-pgsql-operator
      tag_prefix: dis-pgsql-v
      platforms: "linux/amd64"
      workdir: ./services/dis-pgsql-operator
  build-release-flux-oci-latest:
    name: Build latest from main
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ./services/dis-pgsql-operator/config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Push latest flux oci image from main
        uses: ./actions/flux/build-push-image
        with:
          workdir: ./services/dis-pgsql-operator/config
          image_name: ${{ env.FLUX_ARTIFACT_NAME }}
          tag: latest
          azure_subscription_id: ${{ secrets.AZURE_ALTINNACR_SUBSCRIPTION_ID }}
          azure_app_id: ${{ secrets.AZURE_ALTINNACR_APP_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
  build-release-flux-oci-release:
    name: Build release from tag
    if: startsWith(github.ref, 'refs/tags/kustomize-dis-pgsql-')
    environment: flux-release
    defaults:
      run:
        working-directory: ./services/dis-pgsql-operator/config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Setup vars
        id: vars
        run: |
          tag=${GITHUB_REF/refs\/tags\/kustomize-dis-pgsql-/}
          echo "tag=${tag}" >> ${GITHUB_OUTPUT}
      - name: Push latest flux oci image from main
        uses: ./actions/flux/build-push-image
        with:
          workdir: ./services/dis-pgsql-operator/config
          image_name: ${{ env.FLUX_ARTIFACT_NAME }}
          tag: ${{ steps.vars.outputs.tag }}
          azure_subscription_id: ${{ secrets.AZURE_ALTINNACR_SUBSCRIPTION_ID }}
          azure_app_id: ${{ secrets.AZURE_ALTINNACR_APP_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
