name: Release and promote Flux oci releases

on:
  issues:
    types:
      - edited
  release:
    types:
      - created
  push:
    branches:
      - main
    paths:
      - flux/releaseconfig.json
      - .github/workflows/flux-manage-releases.yml
  workflow_dispatch: 
    inputs:
      tag_name:
        required: true
        type: string
      release_url:
        required: true
        type: string
      release_sha:
        required: true
        type: string
permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{github.event.issue.number || github.ref}}-${{github.event.release.tag_name || github.event.inputs.tag_name}}
  cancel-in-progress: true

env:
  ISSUE_TITLE_PREFIX: "Gitops OCI image promotion:"
  RELEASE_TAG_PREFIX: "flux-oci-"
  RELEASE_FILE: "flux/releaseconfig.json"
  LABEL: "flux-release"

jobs:
  create-issue:
    runs-on: ubuntu-latest
    if: (github.event_name == 'release' && github.event.action == 'created' && startsWith(github.event.release.tag_name, 'flux-oci-')) || (github.event_name == 'workflow_dispatch' && startsWith(github.event.inputs.tag_name, 'flux-oci-'))
    steps:
      - name: Create issue
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const tag = (github.event_name == 'release' ? github.event.release.tag_name :context.payload.inputs.tag_name);
            const version = tag.match(/v\d+\.\d+\.\d+(?:-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?(?:\+[0-9A-Za-z-]+)?$/)[0];
            const appName = tag.replace('app-', '').replace(`-${version}`, '');
            const releaseUrl = (github.event_name == 'release' ? github.event.release.html_url : context.payload.inputs.release_url);
            const releaseCreator = context.payload.release?.author?.login;
            const issueTitle = `${{ env.ISSUE_TITLE_PREFIX }} ${appName} version ${version}`;
            const issueBody = `A new release has been published. Check it out [here](${releaseUrl})
            - App Name: ${appName}
            - Version: ${version}
            - Release Tag: ${tag}
            - Release URL: ${releaseUrl}

            To create a pull request with updated release config file, please check the boxes below:
            <!-- start-env-list -->
            - [ ] Deploy to at_ring1
            - [ ] Deploy to at_ring2
            - [ ] Deploy to tt_ring1
            - [ ] Deploy to tt_ring2
            - [ ] Deploy to prod_ring1
            - [ ] Deploy to prod_ring2
            <!-- stop-env-list -->
            `;
            // Check if the issue already exists
            const { data: issues } = await github.rest.issues.listForRepo({
              ...context.repo,
              state: 'open',
              labels: '${{ env.LABEL }}',
            });
            const issueExists = issues.some(issue => issue.title === issueTitle);
            if (issueExists) {
              console.log(`Issue already exists: ${issueTitle}`);
              return;
            }
            // Create a new issue
            const response = await github.rest.issues.create({
              ...context.repo,
              title: issueTitle,
              body: issueBody,
              labels: [ '${{env.LABEL}}' ],
              assignees: releaseCreator ? [releaseCreator] : [],
            });
            console.log(`Issue created: ${response.data.html_url}`);
  create-release-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'edited' && startsWith(github.event.issue.title, 'Gitops OCI image promotion:') && github.event.issue.draft == false && github.event.issue.state == 'open'
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Promote release
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        id: update-release
        with:
          script: |
            const issueTitle = context.payload.issue.title
            const versionRegex = /${{ env.ISSUE_TITLE_PREFIX }} ${{ env.RELEASE_TAG_PREFIX }}(.*?) version v(\d+\.\d+\.\d+)$/;
            const match = issueTitle.match(versionRegex);
            if (!match) {
              console.log('No version found in release tag:', issueTitle);
              return;
            }
            const releaseName = match[1];
            const releaseVersion = match[2];
            core.setOutput('release-name', releaseName);
            core.setOutput('release-version', releaseVersion);

            const currentState = context.payload.issue.body;
            // find the checkboxes in the issue body starting with <!-- start-env-list --> and ending with <!-- stop-env-list -->
            const startEnvList = currentState.indexOf('<!-- start-env-list -->');
            const stopEnvList = currentState.indexOf('<!-- stop-env-list -->');
            const envList = currentState.substring(startEnvList + 23, stopEnvList);
            const envListLines = envList.split('\n').map(line => line.trim());
            const lineRegex = /- \[([ x])\] Deploy to (.+)$/;
            const envListCheckboxes = envListLines.map(line => {
              const match = line.match(lineRegex);
              if (match) {
                const checked = match[1] === 'x';
                const env = match[2];
                return { env, checkbox: checked };
              }
              return null;
            }).filter(Boolean);
            // Update releases config file and create new Pull Request
            const releasesConfigFile = `${{ env.RELEASE_FILE }}`;
            const releasesConfig = require(`./${releasesConfigFile}`);
            // Update environments in releases config file
            envListCheckboxes.forEach(env => {
              if (env.checkbox) {
                const envName = env.env.toLowerCase();
                if (!releasesConfig[releaseName]) {
                  releasesConfig[releaseName] = {};
                }
                releasesConfig[releaseName][envName] = releaseVersion;
              }
            });

            // Write the updated config back to the file
            const fs = require('fs');
            fs.writeFileSync(releasesConfigFile, JSON.stringify(releasesConfig, null, 2));
            console.log('Updated releases config:', releasesConfig);
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412 # v7.0.9
        id: create-pr
        with:
          title: "release: deploy version ${{ steps.update-release.outputs.release-version }} for the ${{ steps.update-release.outputs.release-name }} config"
          body: "This pull request updates the releases config file with the new release version.\nOnce this is merged the changes will be deployed to the selected environments."
          base: main
          commit-message: "release: deploy version ${{ steps.update-release.outputs.release-version }} for the ${{ steps.update-release.outputs.release-name }} config"
          branch: update-releases-config-${{ steps.update-release.outputs.release-name }}-${{ steps.update-release.outputs.release-version }}
          delete-branch: true
          labels: "${{ env.LABEL }}"
          sign-commits: true
      - name: Add comment to issue
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const issueNumber = context.payload.issue.number;
            // Check if the comment already exists
            const { data: comments } = await github.rest.issues.listComments({
              ...context.repo,
              issue_number: issueNumber
            });
            const commentPrefix = 'A pull request has been created to update the releases config file.';
            // Update the comment if it already exists
            const existingComment = comments.find(comment => comment.body.startsWith(commentPrefix));
            if (existingComment) {
              console.log('Updating existing comment:', existingComment.id);
              if ('${{ steps.create-pr.outputs.pull-request-operation }}' == 'closed') {
                await github.rest.issues.deleteComment({
                  ...context.repo,
                  comment_id: existingComment.id
                });
              } else {
                await github.rest.issues.updateComment({
                  ...context.repo,
                  comment_id: existingComment.id,
                  body: `${commentPrefix} Check it out ${{ steps.create-pr.outputs.pull-request-url }}`
                });
              }
            } else {
              if ('${{ steps.create-pr.outputs.pull-request-operation }}' == 'closed') {
                console.log('Pull request was closed, not adding comment.');
                return;
              }
              await github.rest.issues.createComment({
                ...context.repo,
                issue_number: issueNumber,
                body: `${commentPrefix} Check it out ${{ steps.create-pr.outputs.pull-request-url }}`
              });
            }
  generate-matrix:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Generate matrix
        id: generate-matrix
        run: |
          # Read the releases config file and generate matrix
          releasesConfigFile="${{ env.RELEASE_FILE }}"
          matrix=$(jq -c '[to_entries[] | {release: .key, environments: .value}]' $releasesConfigFile)
          echo "matrix={\"include\":$matrix}" >> $GITHUB_OUTPUT
          echo "Generated matrix: $matrix"

  retag-release:
    runs-on: ubuntu-latest
    needs: generate-matrix
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
    environment: flux-release
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Prepare Job for Pushing Flux OCI Artifacts to Azure Container Registry
        id: setup_flux_acr
        uses: ./actions/flux/setup-flux-acr
        with:
          azure_app_id: ${{ secrets.AZURE_ALTINNACR_APP_ID }}
          azure_subscription_id: ${{ secrets.AZURE_ALTINNACR_SUBSCRIPTION_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      - name: Promote release
        env:
          REGISTRY: altinncr.azurecr.io
        run: |
          echo "Promoting release ${{ matrix.release }} for all environments"
          echo '${{ toJson(matrix.environments) }}' | jq -r 'to_entries[] | "\(.key) \(.value)"' | while read environment version; do
            echo "retagging oci://${REGISTRY}/manifests/infra/${{ matrix.release }}:${version} to ${environment}"
            flux tag artifact oci://${REGISTRY}/manifests/infra/${{ matrix.release }}:${version} \
            --tag ${environment} \
            --provider=azure
          done
