name: Lakmus Lint and Test

on:
  push:
    branches:
      - main
    paths:
      - services/lakmus/**
      - .github/workflows/lakmus-lint-test.yml
  pull_request:
    branches:
      - main
    paths:
      - services/lakmus/**
      - .github/workflows/lakmus-lint-test.yml

permissions:
  contents: read

jobs:
  lint-and-test:
    name: Lint and Test on Ubuntu
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/lakmus
    steps:
      - name: Clone the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: 'services/lakmus/go.mod'
          cache-dependency-path: 'services/lakmus/go.sum'

      - name: Run linter
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: v2.4.0
          working-directory: services/lakmus

      - name: Running Tests
        run: |
          make tidy
          make test
