name: Scan/Release tf azure devops agent Image

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/terraform-azdev-agent-release.yml
      - infrastructure/images/terraform-azure-devops-agent/**
      - .github/workflows/reusable-image-scan-and-release-ghcr.yml
  push:
    tags:
      - "tf-azdev-agent-*"
    branches:
      - main
    paths:
      - .github/workflows/terraform-azdev-agent-release.yml
      - infrastructure/images/terraform-azure-devops-agent/**
      - .github/workflows/reusable-image-scan-and-release-ghcr.yml
  workflow_dispatch: {}
permissions:
  contents: read
  packages: write

jobs:
  build-and-release:
    name: Build, scan and release
    uses: ./.github/workflows/reusable-image-scan-and-release-ghcr.yml
    with:
      release_latest: false
      image_name: terraform-azure-devops-agent
      tag_prefix: tf-azdev-agent-
      workdir: ./infrastructure/images/terraform-azure-devops-agent
      platforms: linux/amd64
